kubernetes-intro
otus-kuber-2020-04/dmizverev_platform pull request #2
Opened 2020-05-01 16:46 UTC by dmizverev

# Выполнено ДЗ №2

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Ответ на вопрос о восстанвлении pod
Предположу, что: 
kube-apiserver - это static Pod. За его восстановлением следит непосредственно kubelet.
См. https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/
За восстановление cor-edns, kube-dns отвечает AddonManager, он реагирует на restartpolicy.

 - Создан dockerfile с web server
 - Создан pod для запуска web server с init-container
 - Созданы pod для запуска frontend heapster

## Как запустить проект:
 `kubectl apply -f kubernetes-intro/web-pod.yaml`
 `kubectl apply -f kubernetes-intro/frontend-pod-healthy.yaml`

## Как проверить работоспособность:
 - Перейти по ссылке http://localhost:8000

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-05-01 16:58 UTC, dmizverev commented
Столкнулся с проблемой из https://otus-devops.slack.com/archives/G0121KP3J03/p1588328780102900

2020-05-05 05:15 UTC, Jasstkn requested changes
Доброе утро! В домашнем задании необходимо было создать pod с именем web (по имени происходит проверка дз, смотрите слайд 2.14) Напишу ревью финальное после того, как поправите недочет =)

2020-05-05 07:01 UTC, dmizverev commented
@Jasstkn , добрый день.
Я исправил имя Pod. Тем не менее получил ошибку
Вы могли бы подсказать, какой Pod не может запуститься?
```
==================================== ERRORS ====================================
__________________ ERROR at setup of test_resource_existence ___________________
additional-tests/test_110_frontend_pod.py:16: in frontend_pod
    p.wait_until_containers_start(timeout=60)
/tmp/pytest/lib/python3.6/site-packages/kubetest/objects/pod.py:289: in wait_until_containers_start
    utils.wait_for_condition(condition=wait_condition, timeout=timeout, interval=1)
/tmp/pytest/lib/python3.6/site-packages/kubetest/utils.py:114: in wait_for_condition
    .format(timeout, condition)
E   TimeoutError: timed out (60s) while waiting for condition <Condition (name: all pod containers started, met: False)>
____________________ ERROR at setup of test_resource_status ____________________
additional-tests/test_110_frontend_pod.py:16: in frontend_pod
    p.wait_until_containers_start(timeout=60)
/tmp/pytest/lib/python3.6/site-packages/kubetest/objects/pod.py:289: in wait_until_containers_start
    utils.wait_for_condition(condition=wait_condition, timeout=timeout, interval=1)
/tmp/pytest/lib/python3.6/site-packages/kubetest/utils.py:114: in wait_for_condition
    .format(timeout, condition)
E   TimeoutError: timed out (60s) while waiting for condition <Condition (name: all pod containers started, met: False)>
```

2020-05-05 07:31 UTC, dmizverev commented
@Jasstkn 
Исправил ошибку самостоятельно, просто пересобрав image. Делаю merge

2020-05-05 07:31 UTC, merged